# Generated by Django 6.0 on 2026-06-02 16:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facility', '0484_remove_facility_discount_codes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FacilityEncounterIdentifierConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('history', models.JSONField(default=dict)),
                ('meta', models.JSONField(default=dict)),
                ('pattern', models.CharField(help_text='Format string. Allowed tokens: {FAC_CODE}, {YYYY}, {YY}, {MM}, {DD}, {SEQ}, {CLASS}, {CLASS_TEXT}. Example: {CLASS_TEXT}-{FAC_CODE}-{YYYY}-{SEQ:06d}', max_length=128)),
                ('facility_code', models.CharField(blank=True, max_length=16)),
                ('enabled_encounter_classes', models.JSONField(blank=True, default=list, help_text='Encounter class codes for which identifiers are generated. Empty list enables all encounter classes.')),
                ('reset_period', models.CharField(choices=[('none', 'none'), ('yearly', 'yearly'), ('monthly', 'monthly'), ('daily', 'daily')], default='yearly', max_length=16)),
                ('created_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('facility', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hmis_encounter_identifier_config', to='facility.facility')),
                ('updated_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EncounterIdentifierSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bucket', models.CharField(default='', max_length=16)),
                ('last_value', models.BigIntegerField(default=0)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facility.facility')),
            ],
            options={
                'unique_together': {('facility', 'bucket')},
            },
        ),
    ]
