# Generated by Django 6.0 on 2026-06-02 22:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0077_tagconfig_metadata'),
        ('encounter_identifiers', '0001_initial'),
        ('facility', '0484_remove_facility_discount_codes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EncounterIdentifierAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=100)),
                ('bucket', models.CharField(default='', max_length=16)),
                ('sequence', models.BigIntegerField()),
                ('pattern', models.CharField(max_length=128)),
                ('reset_period', models.CharField(max_length=16)),
                ('allocated_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('encounter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hmis_identifier_allocation', to='emr.encounter')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facility.facility')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('identifier',), name='unique_hmis_encounter_identifier'), models.UniqueConstraint(fields=('facility', 'bucket', 'sequence'), name='unique_hmis_encounter_identifier_seq')],
            },
        ),
    ]
