# Generated by Django 6.0 on 2026-08-20 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('encounter_identifiers', '0002_encounteridentifierallocation'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='encounteridentifierallocation',
            name='unique_hmis_encounter_identifier',
        ),
    ]
